Website URL to UX Design Site-Mapping w/ Walmart: 
https://www.figma.com/proto/cJpDdzog7fvLiM6fJId1hT/SiteMap-Walmart-Re-Design?type=design&node-id=38-57&t=djQ0LZ2mXCG9pXbe-0&scaling=contain&page-id=0%3A1


Figma is my main tool I use but I can also use 
Adobe
Sketch 
WordPress 
and other coding methods in order to make UI's...
